"""Cooperative transparency report model.

One record per (year, quarter) pair — generated by admin, readable by all.
Stores the platform-level financial breakdown for cooperative accountability.
"""

from datetime import datetime

from sqlalchemy import DateTime, Integer, Text, UniqueConstraint, func
from sqlalchemy.orm import Mapped, mapped_column

from app.db.database import Base


class CooperativeReport(Base):
    __tablename__ = "cooperative_reports"
    __table_args__ = (
        UniqueConstraint("year", "quarter", name="uq_cooperative_report_period"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    year: Mapped[int] = mapped_column(Integer, nullable=False)
    quarter: Mapped[int] = mapped_column(Integer, nullable=False)  # 1-4

    # Ride volume
    total_rides: Mapped[int] = mapped_column(default=0)
    total_cancelled_rides: Mapped[int] = mapped_column(default=0)

    # Financial flows
    total_fare_collected_usd: Mapped[float] = mapped_column(default=0.0)
    total_platform_fees_usd: Mapped[float] = mapped_column(default=0.0)
    total_driver_earnings_usd: Mapped[float] = mapped_column(default=0.0)
    total_tips_usd: Mapped[float] = mapped_column(default=0.0)

    # Cooperative health metrics
    platform_fee_rate_pct: Mapped[float] = mapped_column(default=0.0)
    driver_take_rate_pct: Mapped[float] = mapped_column(default=0.0)

    # Member counts for the period
    active_drivers: Mapped[int] = mapped_column(default=0)
    active_riders: Mapped[int] = mapped_column(default=0)
    new_drivers: Mapped[int] = mapped_column(default=0)
    new_riders: Mapped[int] = mapped_column(default=0)

    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)
