"""Corporate Shift Auto-Booking models.

When an employee's shift assignment has ``auto_request_rides = True``, the
platform generates pending auto-booking records for upcoming shift dates.
Admins can then process these bookings (creating actual Ride records) or
cancel them.  Each booking tracks one direction: ``to_work`` (pickup at home,
dropoff at shift work location) or ``from_work`` (reverse).

Models:
  CorporateShiftAutoBooking
      — one record per (assignment, shift_date, direction) combination.

Table:
  corporate_shift_auto_bookings
"""

from __future__ import annotations

import enum
import uuid
from datetime import date, datetime

import sqlalchemy as sa
from sqlalchemy import (
    Boolean,
    Date,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.database import Base


class ShiftAutoBookingStatus(str, enum.Enum):
    """Lifecycle status of a single shift auto-booking record."""

    pending = "pending"      # Generated but not yet processed
    booked = "booked"        # Ride successfully created
    failed = "failed"        # Ride creation attempted but failed
    skipped = "skipped"      # Shift not running on this date (guard)
    cancelled = "cancelled"  # Manually cancelled before processing


class ShiftAutoBookingDirection(str, enum.Enum):
    """Direction of travel for the auto-booked ride."""

    to_work = "to_work"      # Employee home → shift work location
    from_work = "from_work"  # Shift work location → employee home


class CorporateShiftAutoBooking(Base):
    """An auto-booking record for one shift occurrence.

    Generated by the ``generate_shift_auto_bookings`` service for every
    active shift assignment where ``auto_request_rides = True``.  One record
    is created per (assignment, shift_date, ride_direction) combination —
    the unique constraint prevents duplicates across repeated generation runs.

    Attributes:
        id: UUID primary key.
        shift_id: FK to corporate_shifts (CASCADE delete).  Denormalised from
            the assignment for efficient shift-scoped queries.
        assignment_id: FK to corporate_shift_assignments (CASCADE delete).
            The specific assignment that triggered this booking.
        member_id: FK to corporate_account_members (SET NULL).  Denormalised
            for efficient member-scoped filtering.
        account_id: FK to corporate_accounts_v2 (CASCADE delete).  Denormalised
            for account-scoped queries.
        shift_date: The calendar date on which the shift will run.
        ride_direction: ``to_work`` or ``from_work``.
        scheduled_for: UTC datetime the ride should depart.
            For ``to_work``: shift_date + shift_start_time − advance_booking_minutes
            is used as the booking trigger, but ``scheduled_for`` stores the
            intended departure time (shift_start_time on that date).
            For ``from_work``: shift_date + shift_end_time.
        status: Lifecycle status — ``pending`` / ``booked`` / ``failed`` /
            ``skipped`` / ``cancelled``.
        ride_id: FK to rides (SET NULL).  Populated when status = ``booked``.
        failure_reason: Human-readable error when status = ``failed``.
        booked_at: UTC timestamp when the ride was created.
        cancelled_at: UTC timestamp when the booking was cancelled.
        created_at: UTC timestamp when the record was generated.
    """

    __tablename__ = "corporate_shift_auto_bookings"
    __table_args__ = (
        UniqueConstraint(
            "assignment_id", "shift_date", "ride_direction",
            name="uq_corp_shift_auto_booking",
        ),
        Index("ix_corp_sab_shift_id", "shift_id"),
        Index("ix_corp_sab_assignment_id", "assignment_id"),
        Index("ix_corp_sab_member_id", "member_id"),
        Index("ix_corp_sab_account_id", "account_id"),
        Index("ix_corp_sab_account_status", "account_id", "status"),
        Index("ix_corp_sab_scheduled_for", "scheduled_for"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )

    shift_id: Mapped[int] = mapped_column(
        ForeignKey("corporate_shifts.id", ondelete="CASCADE"),
        nullable=False,
    )

    assignment_id: Mapped[int] = mapped_column(
        ForeignKey("corporate_shift_assignments.id", ondelete="CASCADE"),
        nullable=False,
    )

    member_id: Mapped[int | None] = mapped_column(
        ForeignKey("corporate_account_members.id", ondelete="SET NULL"),
        nullable=True,
    )

    account_id: Mapped[int] = mapped_column(
        ForeignKey("corporate_accounts_v2.id", ondelete="CASCADE"),
        nullable=False,
    )

    shift_date: Mapped[date] = mapped_column(Date(), nullable=False)

    ride_direction: Mapped[ShiftAutoBookingDirection] = mapped_column(
        Enum(ShiftAutoBookingDirection, name="shiftautobookingdirection"),
        nullable=False,
    )

    scheduled_for: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )

    status: Mapped[ShiftAutoBookingStatus] = mapped_column(
        Enum(ShiftAutoBookingStatus, name="shiftautobookingstatus"),
        nullable=False,
        default=ShiftAutoBookingStatus.pending,
    )

    ride_id: Mapped[int | None] = mapped_column(
        ForeignKey("rides.id", ondelete="SET NULL"),
        nullable=True,
    )

    failure_reason: Mapped[str | None] = mapped_column(Text, nullable=True)

    booked_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    cancelled_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # ---- Relationships ----

    shift = relationship(
        "CorporateShift", foreign_keys=[shift_id], lazy="raise"
    )
    assignment = relationship(
        "CorporateShiftAssignment", foreign_keys=[assignment_id], lazy="raise"
    )
    account = relationship(
        "BusinessAccount", foreign_keys=[account_id], lazy="raise"
    )
